-- NETFLIX DATA ANALYSIS USING SQL --

--CREATING A SEPARATE DATABSE FOR THIS DATA ANALYSIS OF NETFLIX DATASET USING SQL 
CREATE DATABASE NETFLIX;
USE NETFLIX;

--CREATING THE STRUCTURE OF THE TABLE 
CREATE TABLE netflix (
	show_id	VARCHAR(6),
	type VARCHAR(10),
	title VARCHAR(150),
	director NVARCHAR(MAX),
	cast NVARCHAR(MAX),
	country	VARCHAR(150),
	date_added	VARCHAR(50),
	release_year INT,
	rating	VARCHAR(10),
	duration VARCHAR(15),
	listed_in NVARCHAR(MAX),
	description NVARCHAR(MAX)
	);

-- INSERTING THE DATA INTO THE TABLE CREATED FROM THE REAL NETFLIX DATASET WHICH I IMPORTED IN THE MSSQL
INSERT INTO netflix
SELECT *
FROM dbo.netflix_titles;

SELECT *
FROM netflix;

-- DATA CLEANING --

-- CHECKING FOR THE NULL VALUES --
SELECT 
	COUNT(*) - COUNT(show_id) AS [show_id NULL],
	COUNT(*) - COUNT(type) AS [type NULL],
	COUNT(*) - COUNT(title) AS [title NULL],
	COUNT(*) - COUNT(director) AS [director NULL],
	COUNT(*) - COUNT(cast) AS [cast NULL],
	COUNT(*) - COUNT(country) AS [country NULL],
	COUNT(*) - COUNT(date_added) AS [date_added NULL],
	COUNT(*) - COUNT(release_year) AS [release_year NULL],
	COUNT(*) - COUNT(rating) AS [rating NULL],
	COUNT(*) - COUNT(duration) AS [duration NULL],
	COUNT(*) - COUNT(listed_in) AS [listed_in NULL],
	COUNT(*) - COUNT(description) AS [description NULL]
FROM netflix;

-- DELETING THE ROWS WHERE NULLS VALUES ARE PRESENT IN THE COLUMN OF date_added, rating, or in duration
DELETE FROM netflix
WHERE (
	date_added IS NULL
	OR 
	rating IS NULL
	OR 
	duration IS NULL
	);

-- UPDATING THE NULL VALUES OF directors, cast and country COLUMN
UPDATE netflix
SET director='Unknown'
WHERE director IS NULL;

UPDATE netflix 
SET CAST = 'Unknown'
WHERE cast IS NULL;

UPDATE netflix 
SET country='Unknown'
WHERE country IS NULL;

-- CHECKING FOR THE DUPLICATES VALUE
SELECT *
FROM (
	SELECT *,
	ROW_NUMBER() OVER(
		PARtITION BY show_id
		ORDER BY show_id
		) AS row_num
	FROM netflix
	) AS T1
WHERE row_num>1;
-- NO DUPLICATES WERE FOUND

--DATA EXPLORATION--

-- VIEWING THE TABLE, TO HAVE SOME OVERVIEW
SELECT *
FROM netflix;

--CHECKING THE TOTAL RECORDS IN THE NETFLIX DATSET
SELECT COUNT(*) AS [Total Content]
FROM netflix;

--CHECKING FOR THE DIFFERENT KIND OF TYPES OF SHOWS 
SELECT DISTINCT type AS [Type]
FROM netflix;

SELECT COUNT(*) AS [Total Columns]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'netflix';

-- CHECKING FOR THE NUMBER OF DIRECTORS
SELECT COUNT(DISTINCT director) AS [Total Directors]
FROM netflix;

-- CHECKING FOR THE NUMBER OF COUNTRIES
SELECT COUNT(DISTINCT(country)) AS [Total Countries]
FROM netflix;

-- DATA ANALYSIS AND BUSINESS ANALYSIS

-- Q1. COUNT THE NUMBER OF MOVIES VS TV SHOWS
-- THIS HELPS IN FIGURING OUT THE DISTRIBUTION OF THE SHOWS IN NETFLIX
SELECT 
	type AS [Type], 
	COUNT(*) AS [Total Counts]
FROM netflix
GROUP BY type;
-- HERE, WE CAN SEE THAT THE NUMBER OF MOVIE IS JUST 300% MORE THAN THE NUMBER OF TV SHOWS

-- Q2. FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS
-- HELPS US TO FIND THE UNDER WHAT RATING DOES MOST OF THE TV SHOWS AND MOVIES LIE
SELECT *
FROM (
	SELECT 
		type AS [Type],
		rating AS [Rating],
		--COUNT(*) AS [Total Count],
		RANK() OVER(
			PARTITION BY type
			ORDER BY COUNT(*) DESC
			) AS [Rank]
	FROM netflix
	GROUP BY 
		type,
		rating
	) AS T1
WHERE Rank=1;
-- IT CAN BE SEEN THAT MOST RATING IN MOVIES AND TV SHOWS ARE TV-MA AND TV-MA RESPECTIVELY, SO TV-MA HAS BEEN MOST USED RATING IN BOTH OF THE TYPES

-- Q3. LIST ALL MOVIES RELEASED IN A YEAR
-- HELPS US TO FIND OUT IN WHICH YEAR HOW MANY MOVIES GOT RELEASED
SELECT release_year AS [Release Year], COUNT(*) AS [Total Count]
FROM netflix
GROUP BY release_year
ORDER BY release_year;
-- HERE WE CAN FIGURE IT OUT THAT THE NUMBER OF MOVIES RELEASED PER YEAR HAS BEEN INCREASING PER YEAR GRADUALLY

-- Q4. FIND THE TOP 5 COUNTRIES WITH MOST CONTENT ON NETFLIX
-- HELPS TO FIND OUT WHICH TOP COUNTRIES PRODUCES THE MOST NUMBER OF MOVIES
SELECT TOP 5
	TRIM(value) AS [Country],
	COUNT(*) AS [Total Movies]
FROM netflix
CROSS APPLY STRING_SPLIT(country, ',')
GROUP BY TRIM(value)
HAVING TRIM(value) != 'Unknown'
ORDER BY COUNT(*) DESC;
-- FROM HERE WE CAN FIGURE THIS OUT THAT UNITED-STATES, INDIA, UNITED-KINGDOM, CANADA, AND FRANCE ARE TOP 5 MOVIE PRODUCING COUNTRY IN THE WHOLE WORLD, WHILE USA LEADING THE LIST MAJORILY

-- Q5 IDENTIFY THE LONGEST MOVIE
SELECT top 1 
	title AS [MOVIE],
	CAST(REPLACE(duration,'min','') AS INT) AS [Duration]
FROM netflix
WHERE type = 'movie'
ORDER BY CAST(REPLACE(duration,'min','') AS INT) DESC;
-- FROM HERE WE CAN SEE THAT 'Black Mirror: Bandersnatch' IS THE MOVIE WITH HIGHEST DURATION

-- Q6. FIND CONTENT ADDED IN THE LAST 5 YEARS
SELECT *
FROM netflix
WHERE release_year BETWEEN 2017 AND 2021
ORDER BY release_year;

-- Q7. FIND ALL THE MOVIES DIRECTED BY RAJIV CHILAKA 
-- HELPS US TO SEE THE MOVIE DIRECTED BY RAJIV CHILAKA
SELECT 
	title AS [MOVIE NAME]
FROM netflix
CROSS APPLY STRING_SPLIT(director,',')
WHERE 
	TRIM(value) = 'Rajiv Chilaka'
	AND 
	type = 'Movie';
-- SO, WE CAN SEE THAT THERE ARE TOTAL OF 19 MOVIES WHICH ARE DIRECTED BY RAJIV CHILAKA

-- Q8. LIST ALL THE TV SHOWS WHICH HAVE MORE THAN 5 SEASONS
-- HELPS US FIND OUT THE SERIES WHICH HAVE SO LONG STORY AND MORE SEASONS
SELECT title AS [Series Name]
FROM NETFLIX
WHERE 
	type = 'TV Show'
	AND 
	CAST(TRIM(REPLACE(REPLACE(duration,'Seasons',''),'Season','')) AS INT) > 5
ORDER BY duration DESC;
-- WE CAN FIGURE THIS OUT TTHERE ARE TOTAL OF 96 TV SHOWS WHICH ARE HAVING MORE THAN 5 SEASONS

-- Q9. COUNT THE NUMBERN OF CONTENT ITEMS IN EACH GENRE
-- HELPS US TO FIGURE OUT WHICH GENRE HAS THE MOST CONTENT IN IT 
SELECT
	TRIM(value) AS [Genre],
	COUNT(*) AS [Total Content]
FROM netflix
CROSS APPLY STRING_SPLIT(listed_in,',')
GROUP BY TRIM(value)
ORDER BY COUNT(*) DESC;
-- HERE WE CAN SEE ANY ONE TV SHOW OR MOVIE IS LISTED IN MULTIPLE GENRES, AND AMONG THEM INTERNATIONAL MOVIES IS THE ONE WHICH IS HAVING THE HIGHEST NUMBER OF CONTENTS

-- Q10. FIND EACH YEAR AND THE AVERAGE NUMBER OF CONTENT RELEASE BY INDIA ON NETFLIX RETURN TOP 5 YEAR WITH HIGHEST AVERAGE CONTENT RELEASE
SELECT TOP 5
	YEAR(CAST(date_added AS DATE)) AS [Year Released],
	COUNT(*) AS [Total Content],
	ROUND(COUNT(*)*100.0/
		(
			(
				SELECT COUNT(*) 
				FROM netflix 
				CROSS APPLY STRING_SPLIT(country,',') 
				WHERE TRIM(value)='India'
			)
		)
	,2
	) AS [Percentage]
FROM netflix
CROSS APPLY STRING_SPLIT(country,',')
WHERE TRIM(value) = 'India'
GROUP BY YEAR(CAST(date_added AS DATE))
ORDER BY COUNT(*) DESC;
-- IT CLEARS THAT PRE-COVID WAS THE PERIOD WHEN INDIA PRODUCED MOST CONTENTS

-- Q11. LIST ALL THE MOVIES THAT ARE LISTED IN DOCUMENTARIES
-- HELPS TO FIGURE OUT THE MOVIES WHICH ARE ORIGINALLY A DOCUMENTRY
SELECT * 
FROM netflix
CROSS APPLY STRING_SPLIT(listed_in,',')
WHERE TRIM(Value) = 'Documentaries';
-- SO, WE CAN SEE THAT THERE ARE TOTAL OF 869 CONTENTS WHICH ARE DOCUMENTARIES

-- Q12. FIND ALL CONTENT DIRECTORS WITHOUT ANY DIRECTOR
-- HELPS US TO FIND ROWS WITH UNKNOWN DIRECTORS
SELECT *
FROM netflix
WHERE director = 'Unknown';

-- Q13. FIND HOW MANY MOVIES ACTOR ' SALMAN KHAN' APPEARED IN LAST 10 YEARS
SELECT 
	TRIM(Value) AS [Actor],
	COUNT(*) AS [Appearances]
FROM netflix
CROSS APPLY STRING_SPLIT(cast,',')
WHERE	
	TRIM(Value) = 'Salman Khan'
	AND 
	release_year BETWEEN 2012 AND 2021
GROUP BY TRIM(Value);
-- WE CAN SEE THAT SALMAN KHAN HAD ONLY APPEARNCE IN 3 MOVIES IN LAST 10 YEARS

-- Q14. FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA
-- HELPS TO FIND OUT THE ACTOR WHO IS MOST ACTIVE IN THE MOVIE-INDUSTRY OF INDIA
SELECT TOP 10
	TRIM(a.Value) AS [Actor],
	COUNT(*) AS [Appearances]
FROM netflix
CROSS APPLY STRING_SPLIT(cast,',') a
CROSS APPLY STRING_SPLIT(country,',') b
WHERE	
	TRIM(b.Value) = 'India'
	AND 
	TRIM(a.Value) != 'Unknown'
	AND 
	type = 'Movie'
GROUP BY TRIM(a.Value)
ORDER BY COUNT(*) DESC;
-- HERE WE CAN SEE THAT ANUPAM KHER HAS THE MOST APPEARANCES IN THE INDIAN-MOVIES, FOLLOWED BY SHAH RUKH KHAN AND HENCE THE LIST CONTINUES

-- Q15. CATEGORIZE THE CONTENT BASED ON THE PRESENCE OF THE KEYWORDS 'KILL' AND 'VIOLENCE' IN THE DESCRIPTION FIELD. LABEL CONTENT CONTAINING THESE KEYWORDS AS 'BAD' AND ALL OTHER CONTENT AS 'GOOD'. COUNT HOW MANY ITEMS FALL INTO EACH CATEGORY.
-- HELPS US TO DIFFERENTIATE BETWEEN MOVIES WHICH HAS VIOLENCE AND WHICH DOESN'T
WITH CategoryCTE AS (
	SELECT DISTINCT show_id, title,
	CASE	
		WHEN 
			description LIKE '%kill%' 
			OR 
			description LIKE '%Violence%'
		THEN 'Bad'
		ELSE 'Good'
		END AS [Keyword]
	FROM netflix
	)
SELECT
	Keyword,
	COUNT(*) AS [Total Content]
FROM CategoryCTE
GROUP BY Keyword;
-- HERE WE CAN SEE THAT THERE ARE NEARLY 96.00% GOOD MOVIES AND ONLY 4.00% MOVIES CONTAIN VIOLENCE


-- END OF THE PROJECT --